### ISSUE TITLE
header files not found because installed as wrong version

### ISSUE THREAD

**Issue by step21** [sat-metalab/shmdata#1]
When installing latest version 1.3 for switcher - 
includes are installed as -1.2, which results in switcher not finding files

**Comment by step21** [comment]
In configure.ac I had to set API version from 1.2 to 1.3. This made the switcher configure find the right headers. Not sure if this is switcher's fault as it should look for API version 1.2 if that did not change or if it should be fixed in shmdata.

**Comment by nicobou** [comment]
This was fixed in develop branch, but now in master too. And thank you for reporting this issue !
